# Github required configuration
# -------------------
# lsi: false
# safe: true
# incremental: false
# highlighter: rogue
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
# -------------------

title: Kevin Ingles's Homepage
author:
  name: Kevin Ingles
  email: ingles.27@osu.edu
description: > # this means to ignore newlines until "show_excerpts:"
  Hi! My name is Kevin Ingles, welcome to my homepage!

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: dark

  # generate social links in footer
  social_links:
    github:  ominusliticus

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - cv.md
  - research.md 
  - recreational.md
  - outreach.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  load_paths:
    - _sass
    - bower_components/bootstrap-sass/assets/stylesheets
